name: smalltalkCI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-11, Pharo64-10 ]
        experimental: [ false ]
        include:
          - smalltalk: Pharo64-12
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Run tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v3
    #     with:
    #       name: ${{ matrix.smalltalk }}
